Refinement of the bbr parameter and detection of disk prefixes

diff --git a/debian-dd b/debian-dd
--- a/debian-dd
+++ b/debian-dd
@@ -83,12 +83,10 @@ fi
 echo -ne "\n${aoiBlue}Whether to enable BBR${plain}\n"
 read -p "Please input y/n [Default n]: " enableBBR
 if [[ "$enableBBR" =~ ^[Yy]$ ]]; then
-    # 否则设置 BBR 的值
     bbr_path="/etc/sysctl.d/99-sysctl.conf"
     target="in-target"
-    BBR="$target sed -i '\$anet.core.default_qdisc = fq' $bbr_path;$target sed -i '\$anet.core.rmem_max = 67108848' $bbr_path;$target sed -i '\$anet.core.wmem_max = 67108848' $bbr_path;$target sed -i '\$anet.core.somaxconn = 4096' $bbr_path;$target sed -i '\$anet.ipv4.tcp_max_syn_backlog = 4096' $bbr_path;$target sed -i '\$anet.ipv4.tcp_congestion_control = bbr' $bbr_path;$target sed -i '\$anet.ipv4.tcp_rmem = 16384 16777216 536870912' $bbr_path;$target sed -i '\$anet.ipv4.tcp_wmem = 16384 16777216 536870912' $bbr_path;$target sed -i '\$anet.ipv4.tcp_adv_win_scale = -2' $bbr_path;$target sed -i '\$anet.ipv4.tcp_sack = 1' $bbr_path;$target sed -i '\$anet.ipv4.tcp_timestamps = 1' $bbr_path;$target sed -i '\$akernel.panic = -1' $bbr_path;$target sed -i '\$avm.swappiness = 0' $bbr_path;"
+    BBR="$target sed -i '\$anet.core.default_qdisc = fq' $bbr_path;$target sed -i '\$anet.ipv4.tcp_congestion_control = bbr' $bbr_path;$target sed -i '\$anet.ipv4.tcp_rmem = 8192 262144 536870912' $bbr_path;$target sed -i '\$anet.ipv4.tcp_wmem = 4096 16384 536870912' $bbr_path;$target sed -i '\$anet.ipv4.tcp_adv_win_scale = -2' $bbr_path;$target sed -i '\$anet.ipv4.tcp_collapse_max_bytes = 6291456' $bbr_path;$target sed -i '\$anet.ipv4.tcp_notsent_lowat = 131072' $bbr_path;$target sed -i '\$anet.ipv4.ip_local_port_range = 1024 65535' $bbr_path;$target sed -i '\$anet.core.rmem_max = 536870912' $bbr_path;$target sed -i '\$anet.core.wmem_max = 536870912' $bbr_path;$target sed -i '\$anet.core.somaxconn = 32768' $bbr_path;$target sed -i '\$anet.core.netdev_max_backlog = 32768' $bbr_path;$target sed -i '\$anet.ipv4.tcp_max_tw_buckets = 65536' $bbr_path;$target sed -i '\$anet.ipv4.tcp_abort_on_overflow = 1' $bbr_path;$target sed -i '\$anet.ipv4.tcp_slow_start_after_idle = 0' $bbr_path;$target sed -i '\$anet.ipv4.tcp_timestamps = 1' $bbr_path;$target sed -i '\$anet.ipv4.tcp_syncookies = 0' $bbr_path;$target sed -i '\$anet.ipv4.tcp_syn_retries = 3' $bbr_path;$target sed -i '\$anet.ipv4.tcp_synack_retries = 3' $bbr_path;$target sed -i '\$anet.ipv4.tcp_max_syn_backlog = 32768' $bbr_path;$target sed -i '\$anet.ipv4.tcp_fin_timeout = 15' $bbr_path;$target sed -i '\$anet.ipv4.tcp_keepalive_intvl = 3' $bbr_path;$target sed -i '\$anet.ipv4.tcp_keepalive_probes = 5' $bbr_path;$target sed -i '\$anet.ipv4.tcp_keepalive_time = 600' $bbr_path;$target sed -i '\$anet.ipv4.tcp_retries1 = 3' $bbr_path;$target sed -i '\$anet.ipv4.tcp_retries2 = 5' $bbr_path;$target sed -i '\$anet.ipv4.tcp_no_metrics_save = 1' $bbr_path;$target sed -i '\$anet.ipv4.ip_forward = 1' $bbr_path;$target sed -i '\$afs.file-max = 104857600' $bbr_path;$target sed -i '\$afs.inotify.max_user_instances = 8192' $bbr_path;$target sed -i '\$afs.nr_open = 1048576' $bbr_path;$target sed -i '\$anet.ipv4.tcp_fastopen=3' $bbr_path;"
 else
-    # 如果 enableBBR 的值为 N 或 n，则将 BBR 设置为空
     BBR=""
 fi
 
@@ -97,6 +95,26 @@ root_device=$(df / | awk 'NR==2 {print $1}')
 
 # Extract the partition number from the device number
 partitionr_root_number=$(echo "$root_device" | grep -oE '[0-9]+$')
+
+# Check if any disk is mounted
+if [ -z "$(df -h)" ]; then
+    echo "No disks are currently mounted."
+    exit 1
+fi
+
+# Extract the device name of the root partition
+ROOT_DEVICE=$(df / | grep -oE '/dev/[a-z]+')
+
+# Extract the device prefix (sda or vda)
+DEVICE_PREFIX=$(echo "$ROOT_DEVICE" | grep -oE 'sda|vda')
+
+# Check if the device prefix is present
+if [ -n "$DEVICE_PREFIX" ]; then
+    echo "The root partition is mounted on a device with the prefix: $DEVICE_PREFIX"
+else
+    echo "Could not determine the device naming prefix. Defaulting to sda."
+    DEVICE_PREFIX="sda"
+fi
 
 echo -en "\n${aoiBlue}Download boot file...${plain}\n"
 
@@ -158,7 +176,7 @@ d-i mirror/http/proxy string
 d-i clock-setup/utc boolean true
 d-i clock-setup/ntp boolean true
 d-i time/zone string Asia/Shanghai
-d-i partman-auto/disk string /dev/[sv]da
+d-i partman-auto/disk string /dev/$DEVICE_PREFIX
 d-i partman-auto/method string regular
 d-i partman-lvm/device_remove_lvm boolean true
 d-i partman-md/device_remove_md boolean true
@@ -192,7 +210,7 @@ d-i pkgsel/upgrade select none
 
 d-i grub-installer/grub2_instead_of_grub_legacy boolean true
 d-i grub-installer/only_debian boolean true
-d-i grub-installer/bootdev string /dev/[sv]da
+d-i grub-installer/bootdev string /dev/$DEVICE_PREFIX
 
 ### Write preseed
 d-i preseed/late_command string \
